#
# Module manifest for module 'libps1'
#
# Generated by: Maximilian Gindorfer
#
# Generated on: 02.12.2025 via the `New-ModuleManifest` Cmdlet

@{

  # Script module or binary module file associated with this manifest.
  RootModule            = 'libps1.psm1'

  # Version number of this module.
  ModuleVersion         = '0.0.1'

  # Supported PSEditions
  CompatiblePSEditions  = @('Desktop', 'Core')

  # ID used to uniquely identify this module
  GUID                  = '47d35f6c-b384-4ef6-be84-5a1358ce8773'

  # Author of this module
  Author                = 'Maximilian Gindorfer'

  # Company or vendor of this module
  CompanyName           = 'Ad Noctem Collective'

  # Copyright statement for this module
  Copyright             = '(c) Maximilian Gindorfer. All rights reserved.'

  # Description of the functionality provided by this module
  Description           = 'An MIT-licensed collection of PowerShell scripts'

  # Minimum version of the PowerShell engine required by this module
  #
  # NOTE: We're only compatible with '7.3' version due other versions behaving differntly. See: https://github.com/PowerShell/PowerShell/issues/19795#issuecomment-1592111426
  #
  PowerShellVersion     = '7.3'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # ClrVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  ProcessorArchitecture = 'None'

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules       = @(
    @{ ModuleName = "PSWindowsUpdate"; ModuleVersion = '2.2.1.5' },
    @{ ModuleName = "PSReadLine"; ModuleVersion = '2.4.5' },
    @{ ModuleName = "PSWritePDF"; ModuleVersion = '0.0.20' },
    @{ ModuleName = "PSWriteOffice"; ModuleVersion = '0.2.0' },
    @{ ModuleName = "Transferetto"; ModuleVersion = '1.0.0' },
    # ref: https://learn.microsoft.com/de-de/powershell/dsc/overview/decisionmaker?view=dsc-1.1
    @{ ModuleName = "ActiveDirectoryDsc"; ModuleVersion = '6.7.0' },
    @{ ModuleName = "ComputerManagementDsc"; ModuleVersion = '10.0.0' },
    @{ ModuleName = "SystemLocaleDsc"; ModuleVersion = '1.1.0.0' },
    @{ ModuleName = "Microsoft365DSC"; ModuleVersion = '1.25.1112.1' },
    @{ ModuleName = "xDnsServer"; ModuleVersion = '2.0.0' },
    @{ ModuleName = "NTFSSecurity"; ModuleVersion = '4.2.5' }
  )

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  # ScriptsToProcess = @()

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  # NestedModules = @()

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  FunctionsToExport     = '*'

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport       = '*'

  # Variables to export from this module
  VariablesToExport     = '*'

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport       = '*'

  # DSC resources to export from this module
  # DscResourcesToExport = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData           = @{
    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags                     = @('PowerShell', 'PSEdition_Core', 'PSEdition_Desktop', 'Library', 'Windows', 'Linux', 'MacOS', 'administration', 'installation', 'configuration', 'management', 'dsc')

      # A URL to the license for this module.
      LicenseUri               = 'https://opensource.org/license/mit'

      # A URL to the main website for this project.
      ProjectUri               = 'https://github.com/adnoctem/libps1'

      # A URL to an icon representing this module.
      IconUri                  = 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/Powershell_256.png'

      # ReleaseNotes of this module
      ReleaseNotes             = 'https://github.com/adnoctem/libps1/releases'

      # Prerelease string of this module
      Prerelease               = 'beta'

      # Flag to indicate whether the module requires explicit user acceptance for install/update/save
      RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}

